README.md, setup.cfg, snapshottest/pytest.py, tests/test_pytest.py
I also updated testing docs to reflect `setup.cfg`'s new `[tool:pytest]` section that auto provided suggested pytest options.
=> added cls name to snapshot.test_name (if exists)

setup.cfg
Advantages of wheels
* Faster installation for pure python packages
* Avoids arbitrary code execution for installation -- avoids `setup.py`
* Allows better caching for testing and continuous integration
* Creates `.pyc` files as part of installation to ensure they match the python interpreter used
* More consistent installs across platforms and machines
As snapshot is a pure Python package (no C code), it can safely be distributed as a universal wheel.
When you'd normally run `python setup.py sdist upload`, run instead `python setup.py sdist bdist_wheel upload`.
For general information on wheel and its use, see:
http://pythonwheels.com/
For information on the wheel standard, see PEP 427:
https://www.python.org/dev/peps/pep-0427/
=> Distribute as a universal wheel

README.md, README.rst, snapshottest/module.py, snapshottest/unittest.py, tests/test_pytest.py
Closes #17 
Added support for named snapshots, eg:
```python
snapshot.assertMatch(value [, name = ''])
UnitTestSnapshotTest.assertMatchSnapshot(value [, name = ''])
```
By default, auto-inrcemented counter is used as a name.
=> Support named snapshots

snapshottest/nose.py
`--snapshot-update` updates `cls._snapshot_should_update` while doing test discovery. The actual class variable is `cls.snapshot_should_update` - I spent a lot of time being confused as to why this was updating the class, but it would never update the snapshots :) 
thanks for the project though!  I love snapshots in Jest for testing simple input -> expected output style tests.
=> Fix `--snapshot-update` for nose

snapshottest/diff.py, snapshottest/generic_repr.py, snapshottest/module.py
The snapshot stores objects as GenericRepr, while the value contains the original object. This cannot match, so we format values prior to assertion to then compare GenericReprs to GenericReprs.
=> Fix: asserting objects against snapshots is never successful

snapshottest/django.py
We are setting this instead of snapshot.django.TestCase as this allows users to override the default testcase and still be able to use default TEST_RUNNER. Example usecase would be when they want to use something like APITestCase from [DRF](http://www.django-rest-framework.org)
=> Setting snapshot_should_update of snapshottest.unittest.TestCase

snapshottest/module.py
Fixes issue: #16 
Added encoded argument when handling files. Besides the Unicode issue, this is also a good practice when the intention is for the code to be cross-platform (because the default encoding on Windows differs from the default encoding on Mac/Linux).
=> Fix Unicode characters

snapshottest/module.py, tests/test_module.py
If a snapshots file becomes corrupted, or tries to import missing
packages (e.g., after dependency changes), or is otherwise not loadable,
running the tests should result in an error. (Not silently regenerate
the snapshots file and pass the tests.)
[Makes snapshot code generation error in #44 visible, and addresses
@mprostock's comment in #24.]
=> Don't swallow errors loading snapshots

examples/pytest/snapshots/snap_test_demo.py, examples/pytest/test_demo.py, snapshottest/formatter.py, tests/test_formatter.py
Generating snapshots on Python 2 would create unparseable snapshot
files for unicode text containing newlines.
Fixes #44.
Includes @tupy's PR #39 to fix non-ASCII character handling in single-line strings.
=> Fix Python 2 multiline unicode formatting

setup.py, snapshottest/error.py, snapshottest/module.py, tests/test_snapshot_test.py
SnapshotTest.assert_match had been treating any falsy snapshot value
as though that snapshot had not yet been stored, allowing it to match
anything.
* Add tests to make sure assert_match matches values to themselves,
but not to other values
* Introduce explicit SnapshotNotFound case in assert_match (rather
than treating the non-truthy snapshot as missing)
Fixes #49
=> Don't treat empty (falsy) snapshots as missing

snapshottest/django.py
Does two things:
* Modifies the `snapshot_should_update` variable on `snapshottest.unittest.TestCase`, so tests can inherit from that and updating will still work
* Adds an import for `SimpleTestCase`, which is what you need to use in Django if your tests don't hit the database (django `TestCase` fails if you don't have databases configured)
=> Allow use of alternate Django test cases

setup.cfg, tox.ini
Allow use of tox to simplify testing multiple Python versions.
The test matrix (tox envlist) and commands are largely copied directly
from .travis.yml.
=> Set up tox

.travis.yml, Makefile, README.md, README.rst, bin/convert_documentation, tests/test_pytest.py, tox.ini
This eliminates repetition between `.travis.yml`, `tox.ini` and `README.md`, while also making life a little easier for contributors.
=> Proposal: use Makefile to install deps, test, lint, etc

examples/pytest/snapshots/snap_test_demo.py, examples/pytest/test_demo.py, snapshottest/file.py, snapshottest/formatter.py, snapshottest/formatters.py, snapshottest/generic_repr.py, snapshottest/module.py, tests/test_pytest.py, tests/test_snapshot_test.py
After upgrading to 0b4656a I noticed snapshottest was saving the repr of objects that should be wrapped inside a `GenericRepr`.
After bisecting I found out that b78eb52 relied on the assumption that the `value` argument of `GenericFormatter.format` is always the return of `GenericFormatter.store`, which isn't the case while formatting the items inside dicts, lists and tuples.
Also, after #54 removed `PrettyDiff` usage in `SnapshotTest.assert_match` snapshottest stopped "normalizing" the value before comparing, so it was comparing `GenericRepr` with the actual represented objects.
This PR fixes these issues and also improves support for `defaultdict`, `set` and `frozenset`. It is based on #72 because I needed this fix. (thanks, @lucemia!)
Closes #71
cc @matangover
=> Fix some bugs in GenericFormatter and collection formatters

snapshottest/django.py
Issue #61 
This is a small change to avoid clutter in the terminal when the Django test runner is used without there being any snapshot tests.  Currently, the below output is always displayed even when it is not relevant to the tests that are being run.
```sh
======================================================================
SnapshotTest summary
----------------------------------------------------------------------
======================================================================
```
=> Hide empty test summary in Django

.gitignore, setup.cfg, snapshottest/pytest.py, tests/test_pytest.py
When using `pytest.parametrize` with multiline strings, the new line string literal `\n` causes the test name to change on each test run, which causes unexpected behavior.
Here's an example given the following script `script.py`:
import pytest
def return_one(s):
return 1
@pytest.mark.parametrize(
"s",
[
"singleline",
"""
some
multiline
string
""",
],
)
def test_return_one(snapshot, s):
result = return_one(s)
snapshot.assert_match(result)
When running `pytest script.py` I get `2 snapshots written` which look like this:
snapshots['test_return_one[singleline] 1'] = 1
snapshots['test_return_one[\n        some\n        multiline\n        string\n        ] 1'] = 1
When running `pytest script.py` I get `1 snapshots written` and `1 snapshots deprecated` which returns an invalid python file …
=> Fix pytest parametrize for multiline strings

snapshottest/module.py
Enforce sorting of snapshots when writing to the snapshot file.
This helps creating smaller diffs, as no more "random" reordering
occurs, making code reviews easier.
This may also help with #27
=> Sort written snapshots

setup.py
The version range for fastdiff in setup.py did not comply with [PEP-508](https://www.python.org/dev/peps/pep-0508/)
=> PEP-508 version range for fastdiff

setup.py
```
pytest-cov 2.10.0 has requirement pytest>=4.6, but you'll have pytest 4.1.0 which is incompatible.
```
=> Use newer pytest to fix CI under Python 3.5

snapshottest/diff.py, snapshottest/formatters.py, snapshottest/sorted_dict.py, tests/test_sorted_dict.py
`SortedDict` only allowed named arguments as parameters in the form of `**kwargs`, hence limiting the creation of `SortedDict`s with keys other than strings (fixes #65). This PR replaces `**kwargs` as the main argument to build a `SortedDict` and uses instead a regular dict `values` that can contain anything a regular Python dict could.
The only significant change is that to instantiate a new `SortedDict` now, you don't need to pass in the named arguments, `SortedDict(**value)`, but just the variable, `SortedDict(value)`.
Tests have been added for the `SortedDict` class.
=> Fixes #65. SortedDict now handles keys other than strings.

snapshottest/django.py
=> Extract TestRunner to a mixin so it can be used with alternative base classes

Makefile
The wheel generated by Python 2 seems to be incompatible with
long_description_content_type. However the wheel generated by Python 3
seems to support Python 2 as well. So I think this is generating wheels
for both platforms.
=> Fix publish command

tests/test_snapshot_test.py
Make sure snapshots detect differences between
OrderedDicts with the same elements in a different
order (and don't just coerce all collections to
dicts for comparison purposes).
Closes #48
=> Add tests for OrderedDict snapshots

setup.cfg
Remove universal wheel flag from setup.cfg bdist_wheel config,
because universal wheels must support both Python 2 and 3.[1]
(We can and should still distribute as a non-universal "pure
Python" bdist_wheel because this package does not contain any
compiled platform code.)
[1]: https://packaging.python.org/guides/distributing-packages-using-setuptools/#universal-wheels
=> Update packaging for Python 3-only distribution

tox.ini
=> Drop unsupported Python versions from tox config

.travis.yml, Makefile, README.md, setup.cfg, tox.ini
Several minor fixes and improvements related to addition
of black code formatter:
Makefile:
* Add `make install-tools` target to install development
tooling needed for `make format` and `make lint`
* Add `make develop` target that installs tools and
test package
README:
* Update Contributing section to use `make develop` and
recommend `make format-fix`
* Note availability of tox for local testing on all Python
versions
Travis.yml:
* Remove accidental duplicate `include:` that was preventing
flake8 job from running
* Add names to flake8 and black jobs ("lint" and "format")
to improve build reports
tox.ini:
* Add "format" tox env that runs black
* Change "lint" tox env to use make targets
setup.cfg:
* Update flake8 config with [recommended options for black][1]
compatibility (but can't …
=> Fix developer tooling for black, flake8

examples/django_project/django_project/settings.py, examples/pytest/test_demo.py, setup.cfg, snapshottest/file.py, snapshottest/pytest.py, tests/test_pytest.py
Reformat long doc strings and comments to black's
preferred max-line-length of 88, so that flake8
can use the same setting.
(I'm deliberately noqa-punting on the generated
Django settings.py file.)
=> Match black/flake8 max-line-length

CHANGELOG.md, setup.py
These are the commits: https://github.com/syrusakbary/snapshottest/compare/0.6.0...master
@medmunds mind taking a look at this too?
=> RELEASE 1.0.0b0

CHANGELOG.md
As requested in #91, I looked through the commit history and added changelog details for what happened between 0.5.0 and 0.5.1. 
I will note that despite being marked as a patch version, there were several changes that I considered new features.
I also didn't really go deep into the individual commits and diffs but largely worked from the pull request descriptions as given.
I would be happy to tweak the formatting if you would prefer any changes with that as well
=> Added changelog for 0.5.1

snapshottest/unittest.py
This is required in cases where mixins are used for composing `TestCase`s.
=> fix: adding super().setUp() call to unittest.TestCase

snapshottest/module.py
Use importlib instead of imp, fixes #166
=> Use importlib instead of imp

Makefile, examples/unittest/snapshots/snap_test_using_callback.py, examples/unittest/test_using_callback.py, snapshottest/module.py, tests/test_module.py
This PR introduced simple callbacks which can be used to modify content of the snapshot file before write it.
The main purpose is to allow formatting files (see example with black usage), so it probably can close #89
=> Allow snapshot to be modified before write

snapshottest/formatters.py, tests/test_formatter.py
This patch allows producing more correct output for typed enum values.
See also #120
=> Add typed enums support for TypeFormatter
